stages:
  - build
  - error_clean
  - reggie_short
  - reggie_tracking
  - reggie_long

cache:
  key: "$CI_BUILD_REF"
  paths: 
    - build_gnu/    
    - build_intel/    
    - regressioncheck/examples

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "build": Build with intel/gnu on check-in
# ----------------------------------------------------------------------------------------------------------------------------------------------------
build_gnu:
  stage: build
  tags:
    - withmodules
  script:
    - module load env/gnu ; rm -rf build_gnu || true 
    - mkdir -p build_gnu ; cd build_gnu ; cmake .. -DBOLTZPLATZ_BUILD_HDF5=OFF ; make -j all

build_intel:
  stage: build
  tags:
    - withmodules
  script:
    - module load env/intel ; rm -rf build_intel || true 
    - mkdir -p build_intel ; cd build_intel ; cmake .. -DBOLTZPLATZ_BUILD_HDF5=OFF ; make -j all

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "clean": delete build folders if previous builds fail and exit
# ----------------------------------------------------------------------------------------------------------------------------------------------------
clean:
  stage: error_clean
  tags:
    - withmodules
  script:
    - rm -rf build_gnu
    - rm -rf build_intel
  when: on_failure

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "reggie_short": Run most simple reggie with previous builds on check-in
# ----------------------------------------------------------------------------------------------------------------------------------------------------
gnu:
  stage: reggie_short
  tags:
    - withmodules
  script:
    - module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck

intel:
  stage: reggie_short
  tags:
    - withmodules
  script:
    - module load env/intel ; cd build_intel/bin/ ; ./regressioncheck


# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "reggie_tracking": Build and run tracking examples on nightly
# ----------------------------------------------------------------------------------------------------------------------------------------------------
gnu_tracking:
  stage: reggie_tracking
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_tracking_DSMC -j no-debug ; fi

intel_tracking:
  stage: reggie_tracking
  tags:
    - withmodules
  script:
    - echo "nothing to do";
    # fix h5diff on runner -> libs may be wrongly set in the binary file
    # "/opt/hdf5/hdf5-1.8.17/ifort16/bin/h5diff: symbol lookup error: /opt/hdf5/hdf5-1.8.17/ifort16/bin/h5diff: undefined symbol: ompi_mpi_char";
    #- if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_tracking_DSMC -j no-debug ; fi

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "reggie_long": Build and run
#                         - basic PIC tests
#                         - build all specified compile options in "run_basic"
#                         - h-p-convtests
#                         - compile HDF5
#                      examples on nightly
# ----------------------------------------------------------------------------------------------------------------------------------------------------
gnu_mpi:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build -j no-debug ; fi

gnu_PIC:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_PIC -j no-debug ; fi

gnu_TWT:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_TWT_recordpoints -j no-debug ; fi

gnu_convtest:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_convtest -j no-debug ; fi


gnu_HDF5_single_mpi:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build build_HDF5_single_MPI -j no-debug ; fi



intel_mpi:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build -j no-debug ; fi

intel_PIC:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - echo "nothing to do";
    # fix h5diff on runner -> libs may be wrongly set in the binary file
    # "/opt/hdf5/hdf5-1.8.17/ifort16/bin/h5diff: symbol lookup error: /opt/hdf5/hdf5-1.8.17/ifort16/bin/h5diff: undefined symbol: ompi_mpi_char";
    #- if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_PIC -j no-debug ; fi

intel_TWT:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - echo "nothing to do";
    # fix h5diff on runner -> libs may be wrongly set in the binary file
    #- if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_TWT_recordpoints -j no-debug ; fi

intel_convtest:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_convtest -j no-debug ; fi

intel_HDF5_single_mpi:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build build_HDF5_single_MPI -j no-debug ; fi

