stages:
  - build
  - error_clean
  - reggie_checkin
  - reggie_feature_checkin
  - reggie_tracking_nightly
  - reggie_nightly
  - reggie_weekly

cache:
  key: "$CI_BUILD_REF"
  paths: 
    - build_gnu/    
    - build_intel/    
    - regressioncheck/examples

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "build": Build with intel/gnu on check-in
# ----------------------------------------------------------------------------------------------------------------------------------------------------
build_gnu:
  stage: build
  tags:
    - withmodules
  script:
    - module load env/gnu ; rm -rf build_gnu || true 
    - mkdir -p build_gnu ; cd build_gnu ; cmake .. -DBOLTZPLATZ_BUILD_HDF5=OFF ; make -j all

build_intel:
  stage: build
  tags:
    - withmodules
  script:
    - module load env/intel ; rm -rf build_intel || true 
    - mkdir -p build_intel ; cd build_intel ; cmake .. -DBOLTZPLATZ_BUILD_HDF5=OFF ; make -j all

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "clean": delete build folders if previous builds fail and exit
# ----------------------------------------------------------------------------------------------------------------------------------------------------
clean:
  stage: error_clean
  tags:
    - withmodules
  script:
    - rm -rf build_gnu
    - rm -rf build_intel
  when: on_failure

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "reggie_checkin": Run most simple reggie with previous builds on check-in
# ----------------------------------------------------------------------------------------------------------------------------------------------------
gnu:
  stage: reggie_checkin
  tags:
    - withmodules
  script:
    - module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck

intel:
  stage: reggie_checkin
  tags:
    - withmodules
  script:
    - module load env/intel ; cd build_intel/bin/ ; ./regressioncheck


# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "reggie_feature_checkin": Run most simple reggie features with previous builds on check-in (must be very fast)
#                               - feature_PIC_gyrotron_variable_Bz: 1 cell layer gyrotron emission with variable B(z) field
#                               - feature_PIC_single_particle_PML : 4^3 cart box with a particle and 1 cell layer PMLs for all directions
# ----------------------------------------------------------------------------------------------------------------------------------------------------
gnu_PIC_gyrotron_variable_Bz:
  stage: reggie_feature_checkin
  tags:
    - withmodules
  script:
    - module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck run feature_PIC_gyrotron_variable_Bz/

gnu_PIC_single_particle_PML:
  stage: reggie_feature_checkin
  tags:
    - withmodules
  script:
    - module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck run feature_PIC_single_particle_PML/
    
gnu__PIC_IMD_coupling:
  stage: reggie_feature_checkin
  tags:
    - withmodules
  script:
    - module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck run feature_PIC_IMD_coupling/


    
intel_PIC_gyrotron_variable_Bz:
  stage: reggie_feature_checkin
  tags:
    - withmodules
  script:
    - module load env/intel ; cd build_intel/bin/ ; ./regressioncheck run feature_PIC_gyrotron_variable_Bz/
    
intel_PIC_single_particle_PML:
  stage: reggie_feature_checkin
  tags:
    - withmodules
  script:
    - module load env/intel ; cd build_intel/bin/ ; ./regressioncheck run feature_PIC_single_particle_PML/
    
intel__PIC_IMD_coupling:
  stage: reggie_feature_checkin
  tags:
    - withmodules
  script:
    - module load env/intel ; cd build_intel/bin/ ; ./regressioncheck run feature_PIC_IMD_coupling/

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "reggie_tracking_nightly": Build and run tracking examples on nightly
# ----------------------------------------------------------------------------------------------------------------------------------------------------
gnu_tracking:
  stage: reggie_tracking_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_tracking_DSMC -j no-debug ; fi

intel_tracking:
  stage: reggie_tracking_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_tracking_DSMC -j no-debug ; fi

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "reggie_nightly": Build and run
#                         - feature_PIC_single_particle/ : basic PIC test with a single particle in a cart box
#                         - test particle emission for gyrotron setup with fixed electric current of 44 A
#                         - test record points for TWT setup and compare with h5diff
#                         - build all specified compile options in "run_basic" with BUILD_HDF5=ON
#                         - h-p-convtests
#                         - feature_maxwell_dipole_cylinder_PML/ : curved cylinder geometry with PML on axis and dipole in center for testing RP output
#                         - feature_maxwell_dipole_dielectric/ : curved sphere with dielectric region in the center and dipole at near the edge
#                      examples on nightly
# ----------------------------------------------------------------------------------------------------------------------------------------------------
gnu_mpi:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build -j no-debug ; fi

gnu_PIC:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_PIC_single_particle/ -j no-debug ; fi

gnu_emission_gyro:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_emission_gyrotron -j no-debug ; fi

gnu_TWT:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_TWT_recordpoints -j no-debug ; fi

gnu_convtest:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_convtest -j no-debug ; fi

gnu_HDG_turner:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_PIC_HDG_turner/ -j no-debug ; fi

gnu_maxwell_cylinder_PML:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_maxwell_dipole_cylinder_PML/ -j no-debug ; fi

gnu_maxwell_sphere_dielectric:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_maxwell_dipole_dielectric/ -j no-debug ; fi




intel_mpi:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build -j no-debug ; fi

intel_PIC:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_PIC_single_particle/ -j no-debug ; fi

intel_emission_gyro:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_emission_gyrotron -j no-debug ; fi

intel_TWT:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_TWT_recordpoints -j no-debug ; fi

intel_convtest:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_convtest -j no-debug ; fi

intel_HDG_turner:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_PIC_HDG_turner/ -j no-debug ; fi

intel_maxwell_cylinder_PML:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_maxwell_dipole_cylinder_PML/ -j no-debug ; fi

intel_maxwell_sphere_dielectric:
  stage: reggie_nightly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_maxwell_dipole_dielectric/ -j no-debug ; fi

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "reggie_weekly": Build and run examples once a week
#                         - feature_PIC_maxwell_plasma_wave/ : test a plasma-wave with different time-integration and maxwell's equations
# ----------------------------------------------------------------------------------------------------------------------------------------------------
gnu_plasma_wave_maxwell:
  stage: reggie_weekly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_WEEKLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_PIC_maxwell_plasma_wave -j no-debug ; fi

gnu_DSMC_surfflux/:
  stage: reggie_weekly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_WEEKLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_DSMC_surfflux/ -j no-debug ; fi

gnu_DSMC_cylinder/:
  stage: reggie_weekly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_WEEKLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_DSMC_cylinder/ -j no-debug ; fi



intel_plasma_wave_maxwell:
  stage: reggie_weekly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_WEEKLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_PIC_maxwell_plasma_wave -j no-debug ; fi

intel_DSMC_surfflux/:
  stage: reggie_weekly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_WEEKLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_DSMC_surfflux/ -j no-debug ; fi

intel_DSMC_cylinder/:
  stage: reggie_weekly
  tags:
    - withmodules
  script:
    - if [ -n "${DO_WEEKLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_DSMC_cylinder/ -j no-debug ; fi

