stages: 
  - build
  - error_clean
  - reggie_short
  - reggie_tracking
  - reggie_long

cache:
  key: "$CI_BUILD_REF"
  paths: 
    - build_gnu/    
    - build_intel/    
    - regressioncheck/examples

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "build": Build with intel/gnu on check-in
# ----------------------------------------------------------------------------------------------------------------------------------------------------
build_gnu:
  stage: build
  tags:
    - withmodules
  script:
    - module load env/gnu ; rm -rf build_gnu || true 
    - mkdir -p build_gnu ; cd build_gnu ; cmake .. -DBOLTZPLATZ_BUILD_HDF5=OFF ; make all

build_intel:
  stage: build
  tags:
    - withmodules
  script:
    - module load env/intel ; rm -rf build_intel || true 
    - mkdir -p build_intel ; cd build_intel ; cmake .. -DBOLTZPLATZ_BUILD_HDF5=OFF ; make all

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "clean": delete build folders if previous builds fail and exit
# ----------------------------------------------------------------------------------------------------------------------------------------------------
clean:
  stage: error_clean
  tags:
    - withmodules
  script:
    - rm -rf build_gnu
    - rm -rf build_intel
  when: on_failure



# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "reggie_short": Run most simple reggie with previous builds on check-in
# ----------------------------------------------------------------------------------------------------------------------------------------------------
gnu:
  stage: reggie_short
  tags:
    - withmodules
  script:
    - module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck

intel:
  stage: reggie_short
  tags:
    - withmodules
  script:
    - module load env/intel ; cd build_intel/bin/ ; ./regressioncheck
    - cat /home/gitlab-runner/builds/54967830/0/piclas/boltzplatz/build_intel/../regressioncheck/examples/run_basic/std_files_SubEx0001/std-MPIthreads00000002_SubEx0001_iRun0001.out


# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "reggie_tracking": Build and run tracking examples on nightly
# ----------------------------------------------------------------------------------------------------------------------------------------------------
gnu_tracking:
  stage: reggie_tracking
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_tracking_DSMC 2; fi

intel_tracking:
  stage: reggie_tracking
  tags:
    - withmodules
  script:
    #- echo "nothing to do"; # does this work now?
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_tracking_DSMC 2; fi

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "reggie_long": Build and run
#                         - basic PIC tests
#                         - build all specified compile options in "run_basic"
#                         - h-p-convtests
#                         - compile HDF5
#                      examples on nightly
# ----------------------------------------------------------------------------------------------------------------------------------------------------
gnu_PIC:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_PIC 2; fi

gnu_convtest:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_tracking_DSMC_mortar 2; fi
    #- if [ -n "${DO_NIGHTLY}" ]; then  ./regressioncheck build feature_tracking_DSMC_periodic 2; fi

build_gnu_mpi:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build 2; fi

build_gnu_HDF5_single_mpi:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/gnu ; cd build_gnu/bin/ ; ./regressioncheck build feature_tracking_DSMC_mortar 2; fi
   # - if [ -n "${DO_NIGHTLY}" ]; then  ./regressioncheck build feature_tracking_DSMC_periodic 2; fi



intel_PIC:
  stage: reggie_long
  tags:
    - withmodules
  script:
    #- echo "nothing to do"; # does this work now?
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_PIC 2; fi

intel_convtest:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build feature_convtest 2; fi

intel_build_mpi:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build 2; fi

intel_build_mpi:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build 2; fi

build_intel_HDF5_single_mpi:
  stage: reggie_long
  tags:
    - withmodules
  script:
    - if [ -n "${DO_NIGHTLY}" ]; then module load env/intel ; cd build_intel/bin/ ; ./regressioncheck build build_HDF5_single_MPI no-debug 2; fi


