stages: 
  - build
  - error_clean

cache:
  key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
  paths: 
    - build_gnu/    
    - build_intel/    

build_gnu:
  stage: build
  tags:
    - withmodules
  script:
    - module load env/gnu ; module list 
    - mkdir -p build_gnu ; cd build_gnu ; mkdir -p maxwell ; cd maxwell; cmake  ../.. ; make 
    - cd .. ; mkdir -p implicit ; cd implicit; cmake -DBOLTZPLATZ_TIMEDISCMETHOD=ImplicitO4 ../.. ; make 
    - cd .. ; mkdir -p dsmc ; cd dsmc; cmake -DBOLTZPLATZ_TIMEDISCMETHOD=DSMC ../.. ; make 
    - cd .. ; mkdir -p hdg ; cd hdg; cmake -DBOLTZPLATZ_HDG=ON ../.. ; make 

build_intel:
  stage: build
  tags:
    - withmodules
  script:
    - module load env/intel ; module list 
    - mkdir -p build_intel ; cd build_intel ; mkdir -p maxwell ; cd maxwell; cmake ../.. ; make 
    - cd .. ; mkdir -p implicit ; cd implicit; cmake -DBOLTZPLATZ_TIMEDISCMETHOD=ImplicitO4 ../.. ; make 
    - cd .. ; mkdir -p dsmc ; cd dsmc; cmake -DBOLTZPLATZ_TIMEDISCMETHOD=DSMC ../.. ; make 
    - cd .. ; mkdir -p hdg ; cd hdg; cmake -DBOLTZPLATZ_HDG=ON ../.. ; make 

clean:
  stage: error_clean
  tags:
    - withmodules
  script:
    - rm -rf build_gnu  ; rm -rf build_intel
  when: on_failure

